# name of the software
name: Invoke-Documentation
# current version of the software
version: 0.2.0
# licence of the software
license: MIT License
licenseUrl: http://opensource.org/licenses/MIT
# extension of the favicon, blank to disable
favicon:

# default layouts
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "projects"
    values:
      layout: "project"

# list of additional links on the right of the top menu
headerLinks:
  - title: GitHub
    url: https://github.com/Invoke-Automation/Invoke-Documentation
  # - title: Invoke-Automation
  #   url: http://www.invoke-automation.com

# list if additional links on the footer
footerLinks:
  - title: GitHub
    url: https://github.com/Invoke-Automation/Invoke-Documentation
  - title: Issues
    url: https://github.com/Invoke-Automation/Invoke-Documentation/issues?state=open

# header
header:
  color1: "#080331"
  color2: "#673051"
  trianglify: true

# google analytics
analytics:
  account:
  domain:

# github buttons
githubButton:
  user:
  repo:

# twitter buttons
twitter:
  enabled: false
  via:
  hash:
  account:

# facebook buttons
facebook:
  enabled: false
  profileUrl:


exclude: ['README.md', 'LICENSE', 'Gemfile.lock', 'Gemfile']

gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
